### ISSUE TITLE
Overlap list check

### ISSUE THREAD

**Issue by Dev-hoon** [DevSunbo/Vanilar_JS#1]
중복 되는 리스트 체크 후 들어가지 못하도록 막아야 함.

![image](https://user-images.githubusercontent.com/22619283/72034260-d4eed200-32d7-11ea-9583-a0c151ef4390.png)

위와 같이 대소문자 다른 경우도 중복으로 인식되어야 함.
HELLO 와 Hello 는 다른것

**Comment by KIMCOYG** [comment]
대소문자 구분해서 중복 리스트 문제 해결

**Comment by DevSunbo** [comment]
close
