### ISSUE TITLE
one line pixing

### ISSUE THREAD

**Issue by Dev-hoon** [DevSunbo/Vanilar_JS#3]
글자수 제한을 둬서 에러를 남기고, 글자수 초과 및 두줄로 넘어가게 되는 경우 에러를 띄워 한줄로만 보여지도록 고정

**Comment by DevSunbo** [comment]
글자수 입력 제한에 error 하면 거기서 끝나는데 뒷부분 따로 만들어야 함?
그렇게 하면 뭔가 비효율 적인거 같은데..

**Comment by Dev-hoon** [comment]
입력을 방지할것!
리스트에 저장할때가 아니라 입력하다가 글자수 넘어가면 안되게 막아야 함.!!

**Comment by KIMCOYG** [comment]
입력 단계에서 안되도록 하고 막히는 순간 30글자 제한입니다. 메세지 출력
(예를 들어 10글자 제한이면 입력 창에서 11글자가 되는 순간 제한 메세지 출력 및 입력 방지)

**Comment by KIMCOYG** [comment]
앞뒤로 띄어쓰기 잘라주기
글자 수 늘리고
입력 박스 디자인 변경

**Comment by KIMCOYG** [comment]
앞뒤로 띄어쓰기 잘라주기
글자 수 늘리고
입력 박스 디자인 변경
