### ISSUE TITLE
Select and delete

### ISSUE THREAD

**Issue by Dev-hoon** [DevSunbo/Vanilar_JS#4]
부분 적으로 선택해서 삭제 하는 기능 추가

기능 추가 후 개별 삭제 버튼 없애기

**Comment by KIMCOYG** [comment]
셀렉트 후(체크박스 선택 후) 전체 삭제 버튼 누를 떄,
"선택된 것이 있습니다. 전체 삭제 하시겠습니까?"
출력 후 확인 누르면 전체 삭제 아니면 그대로 유지

**Comment by KIMCOYG** [comment]
그냥 전체 삭제및 부분 선택 삭제도 전부 알람 메세지 띄워주기

메세지 내용에 선택 된 리스트 갯수 뛰워주기
00 개의 내용이 지워집니다. (줄바꿈)
정말로 삭제 할래?
